#!/bin/sh

device_pm() {
	printf "Setting device power to %s..." "$1"
	for device in /sys/bus/{pci,spi,i2c}/devices/*/power/control; do
		[ -w "$device" ] || continue
		echo $1 > "$device"
	done
}

case "$1" in
	true) device_pm auto ;;
	false) device_pm on ;;
	*) exit $NA
esac

exit 0
